// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/compiler';
import '@angular/http';
import '@angular/router';
import '@angular/forms';

//import 'jquery';
//import 'lodash';
//import 'angular2-jwt';
//import 'angular2-modal';
//import 'dom-to-image';
//import 'bootstrap-sass';
//import 'font-awesome';
//import 'select2';
//import 'es-module-loader'; 
import 'rxjs';